export const INFO_SAVE_PERSONAL_INFO_LOADING = 'INFO_SAVE_PERSONAL_INFO_LOADING';
export const INFO_SAVE_PERSONAL_INFO = 'INFO_SAVE_PERSONAL_INFO';

export const INFO_SAVE_OFFICE_INFO_LOADING = 'INFO_SAVE_OFFICE_INFO_LOADING';
export const INFO_SAVE_OFFICE_INFO = 'INFO_SAVE_OFFICE_INFO';

export const INFO_SUBMIT_SUCCESS = 'INFO_SUBMIT_SUCCESS';
export const INFO_SUBMIT_FAIL = 'INFO_SUBMIT_FAIL';

 
 